[package]
name = "leadsheetml"
version = "0.1.0"
edition = "2024"

[dependencies]
pest = "2.7.15"
pest_derive = "2.7.15"
clap = { version = "4.5.32", features = ["derive"] }
markup_engine = { version = "0.1.0" }
